source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!

target 'Funnel_Example' do
  pod "Funnel", :path => "../"
end

target 'Funnel_Tests' do
  pod "Funnel", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end
